### ISSUE TITLE
EAN 13 change the number

### ISSUE THREAD

**Issue by jmcsigma** [jbdemonte/barcode#21]
I generate bar code from ID of a items, the items have max lenght of 4 chars, but I fill the other spaces using 0 but when the bar code is generate show another number diferent to the ID. I try in the generator online and the issue is the same. Try using 0000000001998 in the online generator and show 0000000001991.
PD. My english skills are too bad.
![issue](https://cloud.githubusercontent.com/assets/18535413/14611667/09791824-0559-11e6-9571-d1e0e23a8d08.png)

**Comment by jbdemonte** [comment]
Read https://barcode-coder.com/en/ean-13-specification-102.html
The last character is a checksum
