### ISSUE TITLE
Problem with SVG in chrome since version 72

### ISSUE THREAD

**Issue by tuporaqui** [jbdemonte/barcode#27]
There's a parser error when generating a valid code in chrome's latest version:

> This page contains the following errors:
> error on line 1 at column 129: AttValue: ' expected
> Below is a rendering of the page up to the first error.

Probably there are characters that have to be escaped or replaced.

**Comment by xxalfa** [comment]
I will take care of your request, only I need some more information. Could you share a test setup so I understand what happened and changed?

**Comment by tuporaqui** [comment]
Yes, if you check in chrome the online generator:
https://barcode-coder.com/en/barcode-online-generator-2.html
you'll see that the SVG output fails with latest chrome version.

I ended up in this question when looking for a fix for the problem I was facing:
https://stackoverflow.com/questions/54453987/did-chrome-72-break-dataimage-svgxmlutf8-for-css-background-svgs

Thank you, i've fixed my problem using bmp output for now.

**Comment by xxalfa** [comment]
I have analyzed the problem and can now tell you that I recommend two solutions.

```html
<html><body><img src="data:image/svg+xml;base64,P..."></body></html>
```
```html
<html><body><svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="67" height="65"></svg></body></html>
```
I ask for feedback, if this helped?

**Comment by jbdemonte** [comment]
@xxalfa yes, thanks

**Comment by tuporaqui** [comment]
Sorry, I was out a few days, it works, thanks a lot
