### ISSUE TITLE
BMP datamatrix jQuery barcode has incorrect size in header

### ISSUE THREAD

**Issue by robbie-coder** [jbdemonte/barcode#30]
When I create a datamatrix barcode using the jQuery library with version 2.2.0 the bmp image looks correctly on screen but the image size in the bitmap header is incorrect. This causes image parsing libraries like in Java to throw exceptions when parsing the image.

jQuery example to generate the barcode:
`var settings = {
	output: 'bmp',
	moduleSize: 1,
	showHRI: false
};
$('#barcode').barcode('000100011100000100000000ZV2OKP2L3T21F,375886182,305.81', 'datamatrix', settings);
`

When I try to parse it with Java I get this error:
`javax.imageio.IIOException: Invalid width/height for BI_RGB image data.
	at java.desktop/com.sun.imageio.plugins.bmp.BMPImageReader.readHeader(BMPImageReader.java:600)
	at java.desktop/com.sun.imageio.plugins.bmp.BMPImageReader.getWidth(BMPImageReader.java:206)
`

The Java code recently includes a security fix that checks the bitmap size in the header if it is correct see: https://github.com/openjdk/jdk/commit/c70f7cad47c9be0a203079de52ffab0ce53ba965 Although the error messages talks about width and height the real error is the image data size check in that bit of the Java code.

That check fails because the size in the bitmap header is way too small only 782 (hex bytes 0E 03 00 00) while it should be 2134 (hex bytes 56 08 00 00). If I open the bitmap that the barcode library created in Paint and do a save as (still as bitmap) I can see that the size in the header is now correct and now Java doesn't throw the exception.

See the attached [bmp barcodes.zip](https://github.com/jbdemonte/barcode/files/7807156/bmp.barcodes.zip) where one is created from the library and the other is a save as from paint.

**Comment by robbie-coder** [comment]
Could it be that in the jquery-barcode.js digitToBmpRenderer function the way dataLen is calculated is missing the color depth (3)? Line 1207 https://github.com/jbdemonte/barcode/blob/a1d41c91b6d357b9d3786feed0ac4b34ad3283a4/jquery/jquery-barcode.js#L1207

When I change that to add * 3 just like is done in the padding line:
`padding = (4 - ((mw * columns * 3) % 4)) % 4; // Padding for 4 byte alignment ("* 3" come from "3 byte to color R, G and B")
 dataLen = (mw * columns * 3 + padding) * mh * lines;`

It seems to work correctly.

**Comment by xxalfa** [comment]
Thank you for your contribution. Unfortunately, nothing has moved here for a long time. Your analysis looks plausible. Create a pull request and I'll take care of it.
