### ISSUE TITLE
Int25 barcode not being recognized by banks

### ISSUE THREAD

**Issue by lholiveiraa** [jbdemonte/barcode#34]
The barcode is genetated, but when I'm gonna read the barcode an error message is displayed
! [49c37381-2649-4105-bad4-5e21d8741515](https://github.com/jbdemonte/barcode/assets/5816311/59cb815f-c0ce-405a-9980-1d3d007233e2)

**Comment by AlphaOneWhiskeyFour** [comment]
Thank you for your contribution. In general, I can say that this repository works, but the problem lies in the details. It hasn't really been developed further for a long time because there are simply better working examples. I'm willing to help you though, I just need a few more details on how you're using it.

**Comment by lholiveiraa** [comment]
What kind details do you need? I can provide for you.

**Comment by AlphaOneWhiskeyFour** [comment]
You seem young and inexperienced, which is okay. Only you would have to put yourself in my position. As a developer, I need information that brought you to this error message. How exactly was the barcode created, there are several ways. PHP, Java ...

**Comment by lholiveiraa** [comment]
The barcode is created based on a typed line that is generated through a bank function. The typeable line when typed in the bank app is accepted, bringing the billet data.

I'm using jquery-barcode in javascript.

**Comment by AlphaOneWhiskeyFour** [comment]
I can tell you in advance about jquery that it is very outdated and may not work as desired with modern browsers. And I haven't spoken of an app on a smartphone yet. Behind the link below is a website that offers a comprehensive range of barcodes, maybe it will help you.

`https://barcode.tec-it.com/de/Code25IL?data=1234567890`

**Comment by AlphaOneWhiskeyFour** [comment]
If you need more intensive help, you can send me a message via my profile. Otherwise I ask you to close the issue.
